version: '3'
networks:
    maestro:
      driver: bridge
services: 
  sut:
    build: suts/qpid-dispatch
    networks: 
      - maestro
    ports:
      - "48161:8161"
# This is not needed, unless you want to test the
# broker within the container
#      - "45672:5672"
#      - "41616:61616"