version: '3'
services: 
  sut:
    build: suts/qpid-dispatch
    networks: 
      - test
    ports:
      - "48161:8161"
# This is not needed, unless you want to test the
# broker within the container
#      - "45672:5672"
#      - "41616:61616"