version: '3'
networks:
    cluster:
      driver: bridge
    test:
          driver: bridge
services:
  broker:
    build: broker
    networks:
      - cluster
    ports:
      - "18161:8161"
      - "1884:1883"
  sut:
    build: suts/apache-artemis
    networks:
      - test
    ports:
      - "5672:5672"
      - "8161:8161"
      - "61613:61613"
      - "61616:61616"