version: '3'
networks:
    maestro-net:
      driver: bridge
services: 
  maestro-broker:
    build: maestro-broker
    networks: 
      - maestro-net
    ports:
      - "18161:8161"
      # Usually it's not needed to expose MQTT port
      - "1883:1883"
  maestro-sut:
    image: docker.io/rabbitmq:3-management
    networks: 
      - maestro-net
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61616:61616"
#  maestro-receiver:
#    build:
#      context: maestro-worker/maestro-receiver
#      args:
#        - MAESTRO_WORKER_VERSION=devel
#    ports:
#      - "28000:8000"
#    volumes:
#      - ${HOME}/tmp/maestro:/maestro
#    networks:
#      - maestro-net
#    depends_on:
#      - maestro-broker
#      - maestro-sut
#  maestro-sender:
#    build:
#      context: maestro-worker/maestro-sender
#      args:
#        - MAESTRO_WORKER_VERSION=devel
#    ports:
#      - "38000:8000"
#    volumes:
#      - ${HOME}/tmp/maestro:/maestro
#    networks:
#      - maestro-net
#    depends_on:
#      - maestro-receiver
#  maestro-client:
#    build:
#      context: maestro-client
#      args:
#        - MAESTRO_WORKER_VERSION=devel
#    volumes:
#      - ${HOME}/tmp/maestro:/maestro
#    networks:
#      - maestro-net
#    ports:
#      - "8000:8000"
#    depends_on:
#      - maestro-sender
#      - maestro-receiver
#